//-Rota padrão
GET http://localhost:3000
Content-Type: application/json
###

//CheckList
GET http://localhost:3000/checklists
###

//CheckList rota POST
POST http://localhost:3000/checklists
Content-Type: application/json
{
    "task": {
    "nome": "Tarefa 1",
    "done": true
    }
}
###

//CheckList rota GET com parametro
GET http://localhost:3000/checklists/10
Content-Type: application/json
###

//CheckList rota PUT, passando o parametro ID
PUT http://localhost:3000/checklists/10
Content-Type: application/json
###

//CheckList rota DELETE, passando o parametro ID
DELETE http://localhost:3000/checklists/10
Content-Type: application/json
###